### PR TITLE
Remove examples ci needs to keep stages order

### PR DESCRIPTION
**Pull request by pangea-andrest**

### CODE REVIEW

**Review by doubletooth — APPROVED** [review]

**Comment by kenany** [comment]
Why?

**Comment by pangea-andrest** [comment]
> Why?

I'd want to run examples check after unit and integration tests if they success, we should catch implementation errors first and then check if the example keep working

**Comment by pangea-andrest** [comment]
@kenany https://gitlab.com/pangeacyber/pangea-python/-/pipelines/1158241408 this is what happened. All examples run in first stage

**Comment by pangea-andrest** [comment]
Included in https://github.com/pangeacyber/pangea-python/pull/212

**Pull request closed without merging**
